version: "3.7" 
services:
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html/" 
    command: php -S 0.0.0.0:80 -t public/